=== PedroMartz89/dam1/Lenguajes de marcas/2º Trimestre/examen DTD-XSD/xsl/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:simpleType name="tipoDia">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="28"/>
    </xs:restriction>  
  </xs:simpleType>

  <xs:simpleType name="tipoMes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="enero"/>
      <xs:enumeration value="febrero"/>
      <xs:enumeration value="marzo"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="tipoAnyo">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="2000"/>
      <xs:maxInclusive value="2025"/>
    </xs:restriction>  
  </xs:simpleType>

  <xs:simpleType name="tipoNombre">
    <xs:restriction base="xs:string">
      <xs:maxLength value="30"/>
    </xs:restriction>  
  </xs:simpleType>

  <xs:simpleType name="tipoCodPostal">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="(28|41)\d{3}"/>
    </xs:restriction>  
  </xs:simpleType>
  
  <xs:complexType name="tipoNacimiento">
    <xs:attribute name="dia" type="tipoDia"/>
    <xs:attribute name="mes" type="tipoMes"/>
    <xs:attribute name="anyo" type="tipoAnyo"/>
  </xs:complexType>

  <xs:complexType name="tipoDireccion">
    <xs:sequence>
      <xs:element name="calle" type="tipoNombre" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="poblacion" type="tipoNombre" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="provincia" type="tipoNombre" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="codigoPostal" type="tipoCodPostal" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="tipo" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="tipoPersona">
    <xs:sequence>
      <xs:element name="nombre" type="tipoNombre" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="nacimiento" type="tipoNacimiento" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="direccion" type="tipoDireccion" minOccurs="1" maxOccurs="unbounded"/>
      <xs:choice>
        <xs:element name="varon" type="xs:string"/>
        <xs:element name="femenino" type="xs:string"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" type="tipoPersona" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PedroMartz89/dam1/Lenguajes de marcas/2º Trimestre/examen DTD-XSD/xsl/ejercicioExamen.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE personas [

<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, nacimiento?, direccion, (varon | femenino))>
<!ATTLIST persona id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anyo CDATA #REQUIRED>
<!ELEMENT direccion (calle, poblacion, provincia, codigoPostal)>
<!ATTLIST direccion tipo CDATA #REQUIRED>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT codigoPostal (#PCDATA)>
<!ELEMENT varon EMPTY>
<!ELEMENT femenino EMPTY>



]>

<!-- personas.xml -->
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="persona.xsd">
    <persona id="p1">
        <nombre>Juan Pérez González</nombre>
        
        <nacimiento dia="15" mes="enero" anyo="2005"/>
        <direccion tipo="principal">
            <calle>Calle Mayor, 10</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <codigoPostal>28013</codigoPostal>
        </direccion>
        <varon/>
    </persona>
    
    <persona id="p2">
        <nombre>María García</nombre>
        <nacimiento dia="3" mes="marzo" anyo="2010"/>
        <direccion tipo="principal">
            <calle>Avenida de la Constitución, 5</calle>
            <poblacion>Sevilla</poblacion>
            <provincia>Sevilla</provincia>
            <codigoPostal>41001</codigoPostal>
        </direccion>
        <femenino/>
    </persona>
</personas>
